name: release-test

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:

  release-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5
        with:
          # renovate: datasource=golang-version depName=golang
          go-version: '1.23.6'

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@9ed2f89a662bf1735a48bc8557fd212fa902bebf # v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --snapshot --clean --skip=publish -p 1

      - name: Store Releases
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4
        with:
          name: sigstore-kms-alibabakms_v0.0.0-next_linux_amd64.tar.gz
          path: dist/sigstore-kms-alibabakms_v0.0.0-next_linux_amd64.tar.gz

      - name: Store Releases
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4
        with:
          name: sigstore-kms-alibabakms_v0.0.0-next_linux_arm64.tar.gz
          path: dist/sigstore-kms-alibabakms_v0.0.0-next_linux_arm64.tar.gz

      - name: Store Releases
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4
        with:
          name: sigstore-kms-alibabakms_v0.0.0-next_darwin_arm64.tar.gz
          path: dist/sigstore-kms-alibabakms_v0.0.0-next_darwin_arm64.tar.gz

      - name: Store Releases
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4
        with:
          name: sigstore-kms-alibabakms_v0.0.0-next_darwin_amd64.tar.gz
          path: dist/sigstore-kms-alibabakms_v0.0.0-next_darwin_amd64.tar.gz
